root = "."
tmp_dir = "tmp/order"

[build]
  cmd = "go build -o ./tmp/order/order-service ./cmd/order-service"
  bin = "./tmp/order/order-service"
  include_ext = ["go"]
  include_dir = ["cmd/order-service", "internal"]
  exclude_dir = ["tmp", "bin"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
